const HomeText = () => {
  return (
    <div class="px-4 py-5 my-5 text-center">
      <h1 class="display-5 fw-bold text-body-emphasis">
        The Community Showcase
      </h1>
      <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">
          A collection of imaginative and visually stunning images generated by
          DALL-E AI
        </p>
      </div>
    </div>
  );
};
export default HomeText;
